---
- name: Associate NSG with Subnets using Azure CLI
  hosts: localhost
  tasks:
    - name: Associate NSG with subnet 01
      command: >
        az network vnet subnet update
        --resource-group rg-olimpiadas
        --vnet-name vnet-olimpiadas
        --name sub-olimpiadas01
        --network-security-group nsg-olimpiadas
      register: nsg_subnet01

    - name: Associate NSG with subnet 02
      command: >
        az network vnet subnet update
        --resource-group rg-olimpiadas
        --vnet-name vnet-olimpiadas
        --name sub-olimpiadas02
        --network-security-group nsg-olimpiadas
      register: nsg_subnet02

    - name: Display NSG association for subnet 01
      debug:
        var: nsg_subnet01.stdout_lines

    - name: Display NSG association for subnet 02
      debug:
        var: nsg_subnet02.stdout_lines
