---
- name: Create Azure Virtual Network and Subnets using Azure CLI
  hosts: localhost
  tasks:
    - name: Create virtual network
      command: >
        az network vnet create
        --name vnet-olimpiadas
        --resource-group rg-olimpiadas
        --address-prefix 10.0.0.0/16
        --tags Ambiente=Olimpiadas
      register: vnet

    - name: Create subnet 01
      command: >
        az network vnet subnet create
        --resource-group rg-olimpiadas
        --vnet-name vnet-olimpiadas
        --name sub-olimpiadas01
        --address-prefix 10.0.1.0/24
      register: subnet01

    - name: Create subnet 02
      command: >
        az network vnet subnet create
        --resource-group rg-olimpiadas
        --vnet-name vnet-olimpiadas
        --name sub-olimpiadas02
        --address-prefix 10.0.2.0/24
      register: subnet02

    - name: Create Network Security Group
      command: >
        az network nsg create
        --resource-group rg-olimpiadas
        --name nsg-olimpiadas
        --location eastus
        --tags Ambiente=Olimpiadas
      register: nsg

    - name: Display virtual network info
      debug:
        var: vnet.stdout_lines

    - name: Display subnet 01 info
      debug:
        var: subnet01.stdout_lines

    - name: Display subnet 02 info
      debug:
        var: subnet02.stdout_lines

    - name: Display NSG info
      debug:
        var: nsg.stdout_lines
